Description: Build an ANN model for Drug classification.
This project aims to analyze the relationship between various medical parameters and drug effectiveness.
The dataset consists of patient information, including age, sex, blood pressure levels (BP), cholesterol
levels, sodium-to-potassium ratio (Na_to_K), drug type, and corresponding labels. The goal is to develop
a model that can accurately predict the class or category of a given drug based on its features.

In [204]:
#1: Read the dataset and do data pre-processing
import pandas as pd
import numpy as np

In [205]:
data=pd.read_csv('drug200.csv')

In [206]:
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [207]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [208]:
data.isnull().value_counts()

Age    Sex    BP     Cholesterol  Na_to_K  Drug 
False  False  False  False        False    False    200
dtype: int64

In [209]:
data['Drug'].value_counts()

DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64

In [210]:
from sklearn.preprocessing import LabelEncoder

In [211]:
le=LabelEncoder()

In [212]:
data['Sex']=le.fit_transform(data['Sex'])
data['BP']=le.fit_transform(data['BP'])
data['Cholesterol']=le.fit_transform(data['Cholesterol'])
data['Drug']=le.fit_transform(data['Drug'])


In [213]:
data.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [214]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    int64  
 2   BP           200 non-null    int64  
 3   Cholesterol  200 non-null    int64  
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 9.5 KB


In [215]:
x=data.iloc[:,:5].values
x

array([[23.   ,  0.   ,  0.   ,  0.   , 25.355],
       [47.   ,  1.   ,  1.   ,  0.   , 13.093],
       [47.   ,  1.   ,  1.   ,  0.   , 10.114],
       [28.   ,  0.   ,  2.   ,  0.   ,  7.798],
       [61.   ,  0.   ,  1.   ,  0.   , 18.043],
       [22.   ,  0.   ,  2.   ,  0.   ,  8.607],
       [49.   ,  0.   ,  2.   ,  0.   , 16.275],
       [41.   ,  1.   ,  1.   ,  0.   , 11.037],
       [60.   ,  1.   ,  2.   ,  0.   , 15.171],
       [43.   ,  1.   ,  1.   ,  1.   , 19.368],
       [47.   ,  0.   ,  1.   ,  0.   , 11.767],
       [34.   ,  0.   ,  0.   ,  1.   , 19.199],
       [43.   ,  1.   ,  1.   ,  0.   , 15.376],
       [74.   ,  0.   ,  1.   ,  0.   , 20.942],
       [50.   ,  0.   ,  2.   ,  0.   , 12.703],
       [16.   ,  0.   ,  0.   ,  1.   , 15.516],
       [69.   ,  1.   ,  1.   ,  1.   , 11.455],
       [43.   ,  1.   ,  0.   ,  0.   , 13.972],
       [23.   ,  1.   ,  1.   ,  0.   ,  7.298],
       [32.   ,  0.   ,  0.   ,  1.   , 25.974],
       [57.   ,  1. 

In [216]:
y=data.iloc[:,5:6].values
y

array([[0],
       [3],
       [3],
       [4],
       [0],
       [4],
       [0],
       [3],
       [0],
       [0],
       [3],
       [0],
       [0],
       [0],
       [4],
       [0],
       [4],
       [1],
       [3],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [4],
       [2],
       [4],
       [0],
       [4],
       [4],
       [1],
       [4],
       [4],
       [4],
       [0],
       [2],
       [0],
       [4],
       [4],
       [4],
       [1],
       [3],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [2],
       [3],
       [2],
       [0],
       [4],
       [0],
       [0],
       [1],
       [0],
       [4],
       [2],
       [0],
       [1],
       [4],
       [0],
       [0],
       [2],
       [0],
       [4],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [4],
       [2],
       [4],
       [3],
    

In [217]:
from sklearn.model_selection import train_test_split

In [218]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [219]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [220]:
x_train.shape,x_test.shape

((160, 5), (40, 5))

In [221]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [222]:
#2: Build the ANN model with (input layer, min 3 hidden layers & output layer)
model=Sequential()
model.add(Dense(5,activation='relu',kernel_initializer='random_uniform'))#input layer
model.add(Dense(10,activation='relu',kernel_initializer='random_uniform'))#1st hidden layer
model.add(Dense(20,activation='relu',kernel_initializer='random_uniform'))#2nd hidden layer
model.add(Dense(15,activation='relu',kernel_initializer='random_uniform'))#3rd hidden layer
model.add(Dense(5,activation='softmax',kernel_initializer='random_uniform'))#output layer

In [223]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [224]:
model.fit(x_train,y_train,batch_size=32,epochs=300)

Epoch 1/300
5/5 [==============================] - 2s 8ms/step - loss: 1.6083 - accuracy: 0.2625
Epoch 2/300
5/5 [==============================] - 0s 7ms/step - loss: 1.6051 - accuracy: 0.4500
Epoch 3/300
5/5 [==============================] - 0s 7ms/step - loss: 1.6017 - accuracy: 0.4500
Epoch 4/300
5/5 [==============================] - 0s 6ms/step - loss: 1.5983 - accuracy: 0.4500
Epoch 5/300
5/5 [==============================] - 0s 5ms/step - loss: 1.5943 - accuracy: 0.4500
Epoch 6/300
5/5 [==============================] - 0s 7ms/step - loss: 1.5907 - accuracy: 0.4500
Epoch 7/300
5/5 [==============================] - 0s 6ms/step - loss: 1.5860 - accuracy: 0.4500
Epoch 8/300
5/5 [==============================] - 0s 7ms/step - loss: 1.5807 - accuracy: 0.4500
Epoch 9/300
5/5 [==============================] - 0s 6ms/step - loss: 1.5747 - accuracy: 0.4500
Epoch 10/300
5/5 [==============================] - 0s 5ms/step - loss: 1.5684 - accuracy: 0.4500
Epoch 11/300
5/5 [===========

In [225]:
y_pred=model.predict(x_test)

2/2 [==============================] - 0s 7ms/step


In [226]:
y_pred

array([[7.97810973e-09, 5.56311131e-01, 4.33727652e-01, 9.95630864e-03,
        4.74525450e-06],
       [3.12061678e-03, 2.76813572e-10, 6.47571241e-09, 4.93177492e-03,
        9.91947532e-01],
       [9.99999940e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.11540400e-25],
       [9.99999940e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [9.99999940e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.53146285e-23],
       [1.41858798e-03, 3.64791077e-08, 5.21970605e-07, 6.71823099e-02,
        9.31398511e-01],
       [3.20483884e-03, 4.07146261e-10, 9.07673847e-09, 5.67759294e-03,
        9.91117597e-01],
       [1.65205158e-03, 2.20479670e-08, 3.30115967e-07, 4.93016578e-02,
        9.49045956e-01],
       [9.99891579e-01, 7.06493734e-32, 2.64749284e-28, 7.14167836e-16,
        1.08300315e-04],
       [5.26304636e-03, 4.65513773e-11, 1.32277367e-09, 1.86028052e-03,
        9.92876589e-01],
       [3.06287107e-09, 5.7633

In [227]:
y_test

array([[3],
       [4],
       [0],
       [0],
       [0],
       [4],
       [4],
       [4],
       [0],
       [4],
       [1],
       [0],
       [0],
       [0],
       [2],
       [3],
       [0],
       [0],
       [4],
       [0],
       [0],
       [4],
       [4],
       [4],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [4],
       [3],
       [1],
       [4],
       [0],
       [0],
       [4],
       [0],
       [1],
       [4]])

In [245]:
y_test[2]

array([0])

In [246]:
y_pred[2]

array([9.9999994e-01, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       3.1154040e-25], dtype=float32)

In [247]:
o=np.argmax(y_pred[2])
o

0

In [303]:
#3: Test the model with random data
y_p = model.predict((sc.transform([[74.   ,  1.   ,  1.   ,  1.   ,  9.567]])))

1/1 [==============================] - 0s 65ms/step


In [304]:
index=['DrugY','drugX','drugA','drugC','drugB']

In [305]:
p=np.argmax(y_p)

In [306]:
p

4

In [307]:
index[p]

'drugB'